spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

passenger:
  service:
    url: http://passenger-service:8082

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin123}
  email: ${ADMIN_EMAIL:admin@baggage.com}
